import type { Template } from './types'

export const templates: Template[] = [
  {
    id: 'loading-spinner',
    name: 'Loading Spinner',
    description: 'A simple rotating loading indicator',
    category: 'loading',
    thumbnail: '🔄',
    duration: 60,
    frameRate: 30,
    canvasSize: { width: 512, height: 512 },
    objects: [
      {
        localId: 'spinner',
        name: 'Spinner',
        type: 'ellipse',
        visible: true,
        locked: false,
        left: 206,
        top: 206,
        width: 100,
        height: 100,
        fill: 'transparent',
        stroke: '#3b82f6',
        strokeWidth: 8,
        opacity: 1,
      },
    ],
    keyframes: [
      {
        localObjectId: 'spinner',
        frame: 0,
        property: 'rotation',
        value: 0,
        easing: { type: 'linear' },
      },
      {
        localObjectId: 'spinner',
        frame: 60,
        property: 'rotation',
        value: 360,
        easing: { type: 'linear' },
      },
    ],
  },
  {
    id: 'pulse-dot',
    name: 'Pulse Dot',
    description: 'A pulsing notification dot',
    category: 'ui-elements',
    thumbnail: '⭕',
    duration: 30,
    frameRate: 30,
    canvasSize: { width: 512, height: 512 },
    objects: [
      {
        localId: 'dot',
        name: 'Dot',
        type: 'ellipse',
        visible: true,
        locked: false,
        left: 231,
        top: 231,
        width: 50,
        height: 50,
        fill: '#ef4444',
        opacity: 1,
        scaleX: 1,
        scaleY: 1,
      },
    ],
    keyframes: [
      {
        localObjectId: 'dot',
        frame: 0,
        property: 'scale',
        value: [1, 1],
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'dot',
        frame: 15,
        property: 'scale',
        value: [1.3, 1.3],
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'dot',
        frame: 30,
        property: 'scale',
        value: [1, 1],
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'dot',
        frame: 0,
        property: 'opacity',
        value: 1,
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'dot',
        frame: 15,
        property: 'opacity',
        value: 0.7,
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'dot',
        frame: 30,
        property: 'opacity',
        value: 1,
        easing: { type: 'ease-in-out' },
      },
    ],
  },
  {
    id: 'fade-in-up',
    name: 'Fade In Up',
    description: 'Element fades in while moving upward',
    category: 'transitions',
    thumbnail: '⬆️',
    duration: 30,
    frameRate: 30,
    canvasSize: { width: 512, height: 512 },
    objects: [
      {
        localId: 'box',
        name: 'Box',
        type: 'rect',
        visible: true,
        locked: false,
        left: 181,
        top: 256,
        width: 150,
        height: 150,
        fill: '#22c55e',
        rx: 12,
        ry: 12,
        opacity: 0,
      },
    ],
    keyframes: [
      {
        localObjectId: 'box',
        frame: 0,
        property: 'position',
        value: [181, 306],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'box',
        frame: 30,
        property: 'position',
        value: [181, 181],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'box',
        frame: 0,
        property: 'opacity',
        value: 0,
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'box',
        frame: 30,
        property: 'opacity',
        value: 1,
        easing: { type: 'ease-out' },
      },
    ],
  },
  {
    id: 'bounce-ball',
    name: 'Bouncing Ball',
    description: 'A ball that bounces up and down',
    category: 'illustrations',
    thumbnail: '🏀',
    duration: 60,
    frameRate: 30,
    canvasSize: { width: 512, height: 512 },
    objects: [
      {
        localId: 'ball',
        name: 'Ball',
        type: 'ellipse',
        visible: true,
        locked: false,
        left: 206,
        top: 100,
        width: 100,
        height: 100,
        fill: '#f97316',
        opacity: 1,
      },
      {
        localId: 'shadow',
        name: 'Shadow',
        type: 'ellipse',
        visible: true,
        locked: false,
        left: 206,
        top: 400,
        width: 100,
        height: 20,
        fill: '#00000033',
        opacity: 0.3,
        scaleX: 1,
        scaleY: 1,
      },
    ],
    keyframes: [
      {
        localObjectId: 'ball',
        frame: 0,
        property: 'position',
        value: [206, 100],
        easing: { type: 'ease-in' },
      },
      {
        localObjectId: 'ball',
        frame: 15,
        property: 'position',
        value: [206, 300],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'ball',
        frame: 30,
        property: 'position',
        value: [206, 100],
        easing: { type: 'ease-in' },
      },
      {
        localObjectId: 'ball',
        frame: 45,
        property: 'position',
        value: [206, 300],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'ball',
        frame: 60,
        property: 'position',
        value: [206, 100],
        easing: { type: 'ease-in' },
      },
      {
        localObjectId: 'shadow',
        frame: 0,
        property: 'scale',
        value: [0.5, 0.5],
        easing: { type: 'ease-in' },
      },
      {
        localObjectId: 'shadow',
        frame: 15,
        property: 'scale',
        value: [1, 1],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'shadow',
        frame: 30,
        property: 'scale',
        value: [0.5, 0.5],
        easing: { type: 'ease-in' },
      },
      {
        localObjectId: 'shadow',
        frame: 45,
        property: 'scale',
        value: [1, 1],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'shadow',
        frame: 60,
        property: 'scale',
        value: [0.5, 0.5],
        easing: { type: 'ease-in' },
      },
    ],
  },
  {
    id: 'check-mark',
    name: 'Check Mark',
    description: 'Animated success checkmark',
    category: 'icons',
    thumbnail: '✓',
    duration: 30,
    frameRate: 30,
    canvasSize: { width: 512, height: 512 },
    objects: [
      {
        localId: 'circle',
        name: 'Circle',
        type: 'ellipse',
        visible: true,
        locked: false,
        left: 156,
        top: 156,
        width: 200,
        height: 200,
        fill: '#22c55e',
        opacity: 1,
        scaleX: 0,
        scaleY: 0,
      },
      {
        localId: 'check',
        name: 'Check',
        type: 'path',
        visible: true,
        locked: false,
        left: 196,
        top: 236,
        width: 120,
        height: 80,
        stroke: '#ffffff',
        strokeWidth: 12,
        fill: 'transparent',
        opacity: 0,
      },
    ],
    keyframes: [
      {
        localObjectId: 'circle',
        frame: 0,
        property: 'scale',
        value: [0, 0],
        easing: { type: 'ease-out' },
      },
      {
        localObjectId: 'circle',
        frame: 15,
        property: 'scale',
        value: [1.1, 1.1],
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'circle',
        frame: 20,
        property: 'scale',
        value: [1, 1],
        easing: { type: 'ease-in-out' },
      },
      {
        localObjectId: 'check',
        frame: 0,
        property: 'opacity',
        value: 0,
        easing: { type: 'linear' },
      },
      {
        localObjectId: 'check',
        frame: 15,
        property: 'opacity',
        value: 0,
        easing: { type: 'linear' },
      },
      {
        localObjectId: 'check',
        frame: 20,
        property: 'opacity',
        value: 1,
        easing: { type: 'ease-out' },
      },
    ],
  },
]

export function getTemplatesByCategory(category: string): Template[] {
  return templates.filter((t) => t.category === category)
}

export function getTemplateById(id: string): Template | undefined {
  return templates.find((t) => t.id === id)
}

export const templateCategories = [
  { id: 'loading', name: 'Loading', icon: '🔄' },
  { id: 'icons', name: 'Icons', icon: '✨' },
  { id: 'transitions', name: 'Transitions', icon: '↔️' },
  { id: 'ui-elements', name: 'UI Elements', icon: '🎨' },
  { id: 'illustrations', name: 'Illustrations', icon: '🖼️' },
] as const
